# Fastly Compute@Edge package
authors = ["Sm0key"]
description = "Arsenic service at the edge"
language = "nodejs"
manifest_version = 3
name = "arsenic-service"
service_id = ""

[setup]

  [setup.backends]

    [setup.backends."origin"]
      address = "66.179.254.164"
      description = "Primary backend"
      port = 443

  [setup.config_stores]

    [setup.config_stores.auth_config]

      [setup.config_stores.auth_config.items]

        [setup.config_stores.auth_config.items.key]
          description = "API token for backend"
