name = "arsenic-service"
type = "nodejs"
authors = ["Sm0key"]

[setup.backends."origin"]
description = "Primary backend"
address = "66.179.254.164"
port = 443
use_ssl = true

[setup.config_stores."auth_config".items.key]
description = "API token for backend"
input_type = "string"

[edge]
type = "nodejs"
main = "src/index.js"

[build]
build_command = "npm install"
